codio/node-codio

- lib/ns/ns.js
- lib/task-manager.js
- test/task-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-4983
> Batch auth+sub for tasks in codio backend

- README.md
- lib/ns/ns.js
- lib/project-manager.js
- lib/request.js
- lib/task-manager.js
- test/project-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-4840
> [WIP] NS Phase 2

- lib/crypto.js
- lib/project-structure-manager.js
- test/project-structure-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-5156
> Autosave improve

- lib/ns/ns.js
- package.json
https://codio.myjetbrains.com/youtrack/issue/codio-5444
> 5444 Upgrade - Merge from last master

- lib/organization-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-4925
https://codio.myjetbrains.com/youtrack/issue/codio-5410
> 4925 edu teams fixup

- README.md
- lib/organization-manager.js
- test/organization-manager.spec.js
* Add organizationManager.getMembers
> [WIP] New methods for 5526

- lib/project-manager.js
- test/project-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-5869
> Add projects list method for forking feature.

- README.md
- lib/container-manager.js
- lib/import-manager.js
- test/container-manager.spec.js
- test/import-manager.spec.js
Main assessments branch
https://codio.myjetbrains.com/youtrack/issue/codio-5899
> Assessments

- lib/import-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-4958
* the API method was added to do the request to the service.
> state restore api call was added

- lib/import-manager.js
- test/import-manager.spec.js
Ref issue: https://codio.myjetbrains.com/youtrack/issue/codio-6434
> ImportManager: add a importFromS3 API call

- lib/project-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-6509
> Allow update and get Project methods to work without session

- lib/build-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-6648
> Allow to pass format to exportZip.

- lib/ssh-manager.js
- test/ssh-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-6407
> Remove unused code.

- lib/account-manager.js
- lib/organization-manager.js
- test/account-manager.spec.js
- test/organization-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-6654
> [WIP] Speed up apollo

- lib/project-manager.js
- test/project-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-6023
> added setProjectsDisabled method to project-manager

- lib/subscription-manager.js
- test/subscription-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-7129
> Added getSubscription to subscription-manager.js

- lib/organization-manager.js
- test/organization-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-7136
> signed request for createTeam in organization-manager.js

- lib/organization-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-7097
> getOrganizationInternal for OrganizationManager

- lib/organization-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-7188
> Organization members methods are signed.

- lib/account-manager.js
see https://codio.myjetbrains.com/youtrack/issue/codio-7113
> Reset user password via internal request to server

- index.js
- lib/plagiarism-detection-manager.js
- test/plagiarism-detection-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-7211
> plagiarism

- lib/account-manager.js
- test/account-manager.spec.js
see https://codio.myjetbrains.com/youtrack/issue/codio-7173
> LTI integration LMS systems

- lib/organization-manager.js
Server api allow empty value - check in all teams
see https://codio.myjetbrains.com/youtrack/issue/codio-7494
> Check user membership in related org

- lib/import-manager.js
see https://codio.myjetbrains.com/youtrack/issue/codio-7486
> Pass taskId from importFromS3

- lib/project-manager.js
- test/project-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-7714
> add setReadOnly method to project-manager

- lib/project-manager.js
- test/project-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-7753
> Added removeProjects method to project-manager.js

- README.md
- lib/request.js
- package.json
- test/project-manager.spec.js
- test/request.spec.js
- wercker.yml
Multipart form data generate big overhead on memory(with big strings) and generate out of memory error
Use raw post instead
Update request version
see https://codio.myjetbrains.com/youtrack/issue/codio-7871
> Send raw post to server

- lib/ns/ns.js
- package.json
https://codio.myjetbrains.com/youtrack/issue/codio-7882
> Upgrade versions

- lib/project-structure-manager.js
see https://codio.myjetbrains.com/youtrack/issue/codio-7888
> Method for move secure folder to hidden place

- lib/project-manager.js
- lib/project-structure-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-8007
> Add ProjectManager.ensureMounted.

- index.js
- lib/trial-manager.js
Fetch info about dummy data from server
see https://codio.myjetbrains.com/youtrack/issue/codio-8048
> Initialize edu organizations with dummy data

- lib/project-structure-manager.js
- test/project-structure-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-8206
> Remove file templates support

- lib/import-manager.js
- wercker.yml
Update unit call
see https://codio.myjetbrains.com/youtrack/issue/codio-8280
> Unit update workaround

- index.js
- lib/stacks-manager.js
- test/stacks-manager.spec.js
Get stack version by version id
see https://codio.myjetbrains.com/youtrack/issue/codio-8371
> Disable adding docker units to class

- lib/project-manager.js
- lib/stacks-manager.js
- test/project-manager.spec.js
see https://codio.myjetbrains.com/youtrack/issue/codio-8484
> Stack update with unit update

- lib/project-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-8448
> issue #codio-8448. add reply parameters to change stack.

- lib/account-manager.js
https://codio.myjetbrains.com/youtrack/issue/codio-8710
> Allow to exclude extra info from users.

- lib/organization-manager.js
see https://codio.myjetbrains.com/youtrack/issue/codio-8786
> Add Teachers to Class

- lib/project-manager.js
- lib/stacks-manager.js
- test/project-manager.spec.js
- test/stacks-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-8921
> unit publish

- lib/plagiarism-detection-manager.js
- test/account-manager.spec.js
- test/plagiarism-detection-manager.spec.js
- test/request.spec.js
- test/stacks-manager.spec.js
- test/task-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-9368
> added additional fields to plagiarism detection

- lib/ns/ns.js
- package-lock.json
- package.json
see https://codio.myjetbrains.com/youtrack/issue/codio-9835
> Update sockjs related libraries and use specific transports

- lib/account-manager.js
- lib/organization-manager.js
- package-lock.json
- test/account-manager.spec.js
- test/organization-manager.spec.js
see https://codio.myjetbrains.com/youtrack/issue/codio-10068
> User email is blocked on error

- lib/account-manager.js
- lib/project-manager.js
- test/account-manager.spec.js
- test/project-manager.spec.js
- wercker.yml
see https://codio.myjetbrains.com/youtrack/issue/codio-9734
> Request for ability to view users login date

- lib/organization-manager.js
see https://codio.myjetbrains.com/youtrack/issue/codio-10219
> Invite Teacher by email into a class issue

- lib/project-manager.js
see https://codio.myjetbrains.com/youtrack/issue/codio-10300
> mount user workspace folder read-only for read-only projects

- lib/organization-manager.js
- test/organization-manager.spec.js
https://codio.myjetbrains.com/youtrack/issue/codio-10401
> fixed organization-manager getByName method
